name: "Hello World"
description: "Greet someone and record the time"

inputs:
  who-to-greet: # id of the input
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  time: # id of the output
    description: "The time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }} # we pass this an argument to the entrypoint script which fetches it
